export const STACKOVERFLOW_BASE_API_URL = 'http://api.stackexchange.com/2.2';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_STACKOVERFLOW_REQUEST = 'FETCH_STACKOVERFLOW_REQUEST';
export const FETCH_STACKOVERFLOW_FAILURE = 'FETCH_STACKOVERFLOW_FAILURE';
export const FETCH_QUESTIONS_STACKOVERFLOW = 'FETCH_QUESTIONS_STACKOVERFLOW';
export const FETCH_AUTHOR_QUESTIONS_STACKOVERFLOW = 'FETCH_AUTHOR_QUESTIONS_STACKOVERFLOW';
export const FETCH_ANSWERS_FOR_QUESTIONS_STACKOVERFLOW = 'FETCH_ANSWERS_FOR_QUESTIONS_STACKOVERFLOW';
