export const STACKOVERFLOW_BASE_API_URL = 'http://api.stackexchange.com/2.2';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_STACKOVERFLOW_QUESTIONS_REQUEST = 'FETCH_STACKOVERFLOW_QUESTIONS_REQUEST';
export const FETCH_STACKOVERFLOW_QUESTIONS_FAILURE = 'FETCH_STACKOVERFLOW_QUESTIONS_FAILURE';
export const FETCH_STACKOVERFLOW_QUESTIONS_SUCCESS = 'FETCH_STACKOVERFLOW_QUESTIONS_SUCCESS';
