export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const FETCH_STACKOVERFLOW_QUESTIONS_REQUEST = 'FETCH_STACKOVERFLOW_QUESTIONS_REQUEST';
export const FETCH_STACKOVERFLOW_QUESTIONS_FAILURE = 'FETCH_STACKOVERFLOW_QUESTIONS_FAILURE';
export const FETCH_STACKOVERFLOW_QUESTIONS_SUCCESS = 'FETCH_STACKOVERFLOW_QUESTIONS_SUCCESS';
